language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-multiformat-book' ]; then cd .. && eval "mv $currentfolder generator-multiformat-book" && cd generator-multiformat-book; fi

